import os


PROPUBLICA_API_KEY = os.environ.get("PROPUBLICA_API_KEY")
TWEEPY_CONSUMER_KEY = os.environ.get("TWEEPY_CONSUMER_KEY")
TWEEPY_CONSUMER_SECRET = os.environ.get("TWEEPY_CONSUMER_SECRET")
TWEEPY_ACCESS_TOKEN = os.environ.get("TWEEPY_ACCESS_TOKEN")
TWEEPY_ACCESS_TOKEN_SECRET = os.environ.get("TWEEPY_ACCESS_TOKEN_SECRET")
